version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=hadoop_cluster
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode1
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode1_data:/hadoop/dfs/data
    networks:
      - hadoop

  resourcemanager:
      image: bde2020/hadoop-resourcemanager
      container_name: resourcemanager
      depends_on:
        - namenode
      ports:
        - "8088:8088"
      environment:
        - HADOOP_CONF_data__namenode_http___address=namenode:9870
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      networks:
      - hadoop
  
  nodemanager1:
    image: bde2020/hadoop-nodemanager
    container_name: nodemanager1
    depends_on:
      - datanode1
      - resourcemanager
    environment:
      - HADOOP_CONF_data__namenode_http___address=namenode:9870
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    networks:
      - hadoop

volumes:
  namenode_data:
  datanode1_data:


networks:
  hadoop:
    driver: bridge