version: '3'
services:
  pyspark:
    image: jupyter/pyspark-notebook
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - hadoop-network

networks:
  hadoop-network:
    external: true