version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper ## 镜像
    ports:
      - "2181:2181" ## 对外暴露的端口号

  kafka:
    image: wurstmeister/kafka ## 镜像
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 ## 指明 kafka 当前节点监听本机的哪个网卡地址
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 ## 指明客户端连接 kafka 的地址与端口号
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 ## kafka运行是基于zookeeper
