version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'
    networks:
      - hadoop-network

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka_data:/bitnami'
    networks:
      - hadoop-network
    depends_on:
      - zookeeper

  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    networks:
      - hadoop-network
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32m -Xmx64m
    ports:
      - '9000:9000'
    depends_on:
      - kafka


  notebook:
    build: .
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
    ports:
      - 8888:8888
    networks:
      - hadoop-network


volumes:
  zookeeper_data:
    external: false

  kafka_data:
    external: false

networks:
  hadoop-network:
    external: true

