version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper ## 镜像
    networks:
      - hadoop-network

  kafka1:
    image: wurstmeister/kafka ## 镜像
    container_name: kafka1
    networks:
      - hadoop-network
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092 ## 指明 kafka 当前节点监听本机的哪个网卡地址
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092 ## 指明客户端连接 kafka 的地址与端口号 默认为KAFKA_LISTENERS的值
      # KAFKA_LOG_DIR: /kafka ## kafka保存数据的文件夹位置
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 ## kafka运行是基于zookeeper

  kafka2:
    image: wurstmeister/kafka ## 镜像
    container_name: kafka2
    networks:
      - hadoop-network
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092 ## 指明 kafka 当前节点监听本机的哪个网卡地址
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      # KAFKA_LOG_DIR: /kafka ## kafka保存数据的文件夹位置
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 ## kafka运行是基于zookeeper

  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    networks:
      - hadoop-network
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9092
      - JVM_OPTS=-Xms32m -Xmx64m
    ports:
      - '9000:9000'
    depends_on:
      - kafka1
      - kafka2

  notebook:
    build: .
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
    ports:
      - 18888:8888
    networks:
      - hadoop-network


networks:
  hadoop-network:
    external: true

